# Site settings
title: Nguyễn Văn Lắm 
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nguyễn Văn Lắm 
user_description: I have a fondness for developers, and am quite interested in security.
user_title: fresher developer
email: vanlam1412@gmail.com
# twitter_username: lorem_ipsum
instagram_username: vanlam1412
facebook_username: vanlam2001
linkedin_username: nguyen-van-lam-2449441aa
github_username:  vanlam2001
twitter_username: vanlam1412
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
